# Generated by Django 2.1.2 on 2018-12-19 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(max_length=10, verbose_name='称呼')),
                ('name', models.CharField(max_length=200, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('0', '女'), ('1', '男')], default='男', max_length=2, verbose_name='性别')),
                ('email', models.EmailField(max_length=254, verbose_name='电子邮箱')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('information', models.TextField(max_length=1000, verbose_name='主题介绍')),
                ('publication_date', models.DateField(auto_now_add=True, verbose_name='发布时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('authors', models.ManyToManyField(to='showblog.Author')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='出版社')),
                ('address', models.CharField(max_length=100, verbose_name='出版社地址')),
                ('city', models.CharField(max_length=60, verbose_name='出版城市')),
                ('state_province', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=50)),
                ('website', models.URLField(default='http://localhost:8000')),
            ],
            options={
                'verbose_name': '出版社',
                'verbose_name_plural': '出版社',
                'ordering': ['-name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showblog.Publisher'),
        ),
    ]
